### ISSUE TITLE
Publish on bintray

### ISSUE THREAD

**Issue by ascariandrea** [ascariandrea/revolut-scala-sdk#6]
Make the library available on bintray

[http://queirozf.com/entries/publishing-an-sbt-project-onto-bintray-an-example](http://queirozf.com/entries/publishing-an-sbt-project-onto-bintray-an-example)

**Comment by nitrotm** [comment]
I can't find this library on bintray. Is it in 'buildo'? The build.sbt seems to refer to 'ascariandrea' but that organization doesn't exist or is not public.

**Comment by ascariandrea** [comment]
It shouldn't be in buildo, but in 'ascariandrea' organization but maybe I haven't published it properly, I'll check within next days

**Comment by nitrotm** [comment]
Okay, thanks. The following url is empty/not available:

http://dl.bintray.com/ascariandrea/

**Comment by ascariandrea** [comment]
Hey @nitrotm , I've just published the binary!
